###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID lab1-10.eng.utah.edu)
#  Generated on:      Mon Dec  2 20:29:08 2019
#  Design:            core_top_pads
#  Command:           saveDesign DBS/core_top_pads-filled.enc
###############################################################
current_design core_top_pads
create_clock [get_ports {clk}]  -name clk -period 15.000000 -waveform {0.000000 7.500000}
set_propagated_clock  [get_ports {clk}]
